- hosts: monitor-server
  vars:
    prometheus_dir_configuration: "/etc/prometheus"
    prometheus_retention_time: "365d"
    prometheus_scrape_interval: "30s"
    prometheus_node_exporter: true
    prometheus_node_exporter_group: "all"
    prometheus_env: "production"
    prometheus_var_config:
      global:
        scrape_interval: "{{ prometheus_scrape_interval }}"
        evaluation_interval: 5s
        external_labels:
        env: '{{ prometheus_env }}'
      scrape_configs:
        - job_name: prometheus
          scrape_interval: 5m
          static_configs:
            - targets: ['{{ inventory_hostname }}:9090']
  tasks:
    #update-package
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    #install-grafana
    - name: Install nessesary package
      apt: 
        name: apt-transport-https
        state: present
        update_cache: yes

    - name: add grafana gpg key
      shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

    - name: add grafana repo 
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Install grafana
      apt: 
        name: grafana
        state: present
        update_cache: yes

    - name: Enable and start grafana service
      service:
        name: grafana-server
        enabled: yes
        state: started
    #install promethouse
    - name: update and install prometheus
      apt:
        name: prometheus
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    
    - name: prometheus args
      template:
        src: templates/prometheus.j2
        dest: /etc/default/prometheus
        mode: 0644
        owner: root
        group: root

    - name: prometheus configuration file
      template:
        src: templates/prometheus.yaml.j2
        dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
        mode: 0755
        owner: prometheus
        group: prometheus
    
    - name: start prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes
    
    - name: restart_prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
        daemon_reload: yes
    
    # - name: reload_prometheus
    #   uri:
    #     url: http://localhost:9090/-/reload
    #     method: POST
    #     status_code: 200  